### ISSUE TITLE
can't pull spark_master image

### ISSUE THREAD

**Issue by AnShengqiang** [sshakeri/Containerized_Spark#1]
Thanks for your work, it helps a lot! 

I can't pull the spark master image, and I can't find it in the [docker hub](https://hub.docker.com/r/sshakeri/ubuntu/tags) too.
sshakeri/ubuntu:spark_worker is still here, but sshakeri/ubuntu:spark_master is not available.

**Comment by buildcharger** [comment]
Sorry, I noticed the docker file in this repo and built that image successfully, nevermind.
